name: Scheduled Task at 11:45 AM

on:
  schedule:
    # 06:00 UTC is 11:45 AM NPT (Nepal Standard Time)
    - cron: "0 6 * * 1-5"
    #old time
    - cron: "42 5 * * 1-5"
    #new time
    - cron: "20 6 * * 1-5"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my task
        run: |
          echo "Running at 11:45 AM local time  - cron: 20 6 * * 1-5"
          # Add your script execution here